[package]
name = "rpc_server"
version = "0.1.0"
authors = ["ijanus <emekamicro@gmail.com>"]

[dependencies]
jsonrpc-core = "8.0.1"
jsonrpc-http-server = "8.0.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
